algoritmo "semnome"
// Função :
// Autor :
// Data : 09/10/2017
// Seção de Declarações 
var
valor, soma: real
inicio
// Seção de Comandos
soma := 0
ESCREVA ("Digite um valor?")
Leia (valreoor)
ENQUANTO valor <> 0 FACA
          soma := soma + valor
          ESCREVA ("Total: ", soma, " Digite um valor para a soma? ")
          LEIA (valor)
      FIMENQUANTO

      ESCREVA ("Resultado: ", soma)
fimalgoritmo
