algoritmo "semnome"
// Função :
// Autor :
// Data : 28/09/2017
// Seção de Declarações 
var
nota1, nota2, nota3, calc:real
inicio
// Seção de Comandos
Escreva("Escreva o valor do exame?")
Leia(nota1)
Escreva("Escreva o valor do trabalho equiparado?")
Leia(nota2)
Escreva("Escreva o valor do exame final")
Leia(nota3)
calc <- nota1*0.30 + nota2*0.20 + nota3*0.50
Escreva ("A nota final é ", calc)
fimalgoritmo
