algoritmo "semnome"
// Função :
// Autor :
// Data : 09/10/2017
// Seção de Declarações 
var
valor:inteiro
inicio
// Seção de Comandos
Escreva("Escreva um valor?")
Leia(valor)
Escolha valor
       Caso 1,2
            Escreva("Reduzido")
       Caso 3
            Escreva("Médio")
       Caso 4,5
            Escreva("Elevado")
       OutroCaso
            Escreva("Valor Envalido")
FimEscolha
fimalgoritmo
